### PR TITLE
Judá's 1st code review

### PR DESCRIPTION
**Pull request by mrjuda**
Judá's 1st code review on Marcelo's project

### CODE REVIEW

**Comment by mrjuda** [comment]
You're doing great so far.
It's so close to a perfect project.
However, please, kindly fix the following:
- Check your linters.

**Comment by mrjuda** [comment]
Please, kindly fix the following:
- Keep your code clean, deleting unnecessary blank spaces between HTML tags (e.g. the header and the body).

**Review by Gambit142 — CHANGES_REQUESTED** [review]
Hi @mrjuda 👋, 

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Kindly use Github Inline Comments Feature to make comments about a specific line of code. You can click this [link](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request) for directions on how to use inline comments.
- [ ] Kindly phrase the comments politely, as suggestions instead of orders. For example,
  - This is a polite suggestion: *"I think it would be better to use semantic tags"*
  - This reads like an order: *"Use semantic tags"*

- [x] It is a good thumb of rule in reviews to always include reasons for each requested change. For example:
  - This is a well-explained request: *Why don't you use an article tag for the .first-article element instead of a div, that would improve the HTML structure and make the page more accessible*
  - This request lacks a "why": *Why don't you use an article tag here instead of a div?*

### Kindly implement these changes 🙏 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Gambit142 — CHANGES_REQUESTED** [review]
Hi @mrjuda 👋, 

Great work on making the changes requested 👏 
You've done well implementing some of the requested changes, but there is one more that you have not addressed yet.


 ## Required Changes ♻️

- [x] Kindly use _**inline comments**_ for this exercise. Follow these steps:

1. On your page click **Pull Request Button**
2. Then you will see _**Files Changed**_ button
3. Scroll to the file you want to comment on the _**click and drag the + button to the left after the line number**_. It will bring up a _**Comment Box**_ then you type your polite comment explaining why the change should be made
4. Then click _**start a review**_ button. 
5. After all inline comments have been made, scroll up then click _**Finish Review**_ button to indicate whether the pull request is _**Approved**_, _**Requires Change**_ or _**Comment**_.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mrjuda** [comment]
> Hi @mrjuda wave,
> 
> Great work on making the changes requested clap You've done well implementing some of the requested changes, but there is one more that you have not addressed yet.
> ## Required Changes recycle
> 
>     * [x]  Kindly use _**inline comments**_ for this exercise. Follow these steps:
> 
> 
>     1. On your page click **Pull Request Button**
> 
>     2. Then you will see _**Files Changed**_ button
> 
>     3. Scroll to the file you want to comment on the _**click and drag the + button to the left after the line number**_. It will bring up a _**Comment Box**_ then you type your polite comment explaining why the change should be made
> 
>     4. Then click _**start a review**_ button.
> 
>     5. After all inline comments have been made, scroll up then click _**Finish Review**_ button to indicate whether the pull request is _**Approved**_, _**Requires Change**_ or _**Comment**_.
> 
> 
> Cheers and Happy coding!clapclapclap
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Hi, @Gambit142  thanks for the reply. Unfortunately, I only have the "Add review comment" option. So I'll use it to request another fix to the code.

**Review by rotimiazeez — APPROVED** [review]
# Hi @mrjuda >, 

### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
